### ISSUE TITLE
Prepare summary costs estimates

### ISSUE THREAD

**Issue by EneVladMihai** [Miladepour/SyntaxSquad-Project-Kunji#19]
Rough estimates for running costs: Database + Hosting costs + SMS + Email + Auth0

**Comment by haroon-ali-dev** [comment]
complete

**Comment by haroon-ali-dev** [comment]
https://docs.google.com/document/d/1Taeioui0R3WRueluMzUIdiovgztEkvNbXdxRoLUa0tI/edit?usp=sharing
