### ISSUE TITLE
Reasearch google map integrations

### ISSUE THREAD

**Issue by EneVladMihai** [Miladepour/SyntaxSquad-Project-Kunji#22]
This is a research task, we need to understand
* Poential solutions (e.g. location APIs, js map plugings)
* Use Google API to search the address (in a new tab vs maps embbedded into website)
* Constraint: WE ONLY HAVE THE STREET ADDRESS (see spreadsheet)

For each potential solution we need to undertand roughly how much learning it implies / how difficult it is to implement.

**Comment by natyfromwonderland** [comment]
Research has been completed, adding the functionality has been de-prioritised for now.
